server:
  port: 18087
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schedule_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 150.158.213.196
    password: mypassword
  mail:
    host: smtp.qq.com
    username: 2635464756@qq.com
    password: nlpcvnrowslsdhjj
    from: 2635464756@qq.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


#  cloud:
#    alibaba:
#      seata:
#        tx-service-group: my_test_tx_group
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    instance:
      prefer-ip-address: true
feign:
  hystrix:
    enabled: true

#头像地址
head:
  url: https://img.yzcdn.cn/vant/cat.jpeg