server:
  port: 18090
spring:
  application:
    name: schedule
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_schedule?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  redis:
    host: localhost
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
  rabbitmq:
    host: 121.4.91.28
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    #采用手动应答
    listener:
      simple:
        acknowledge-mode: manual
  mail:
    host: smtp.qq.com
    username: 2635464756@qq.com
    password: nlpcvnrowslsdhjj
    from: 2635464756@qq.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  main:
    allow-bean-definition-overriding: true
#  cloud:
#    alibaba:
#      seata:
#        tx-service-group: my_test_tx_group
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    instance:
      prefer-ip-address: true
#feign:
#  hystrix:
#    enabled: true