server:
  port: 18091
spring:
  application:
    name: pay
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 121.4.91.28
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    instance:
      prefer-ip-address: true
# 开启Feign熔断：默认是线程池隔离
feign:
  hystrix:
    enabled: true
# hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enable: true
        isolation:
          strategy: SEMAPHORE


# 微信支付信息配置
weixin:
  #应用ID
  appid: wx8397f8696b538317
  #商户ID
  partner: 1473426802
  #密钥
  partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  #支付回调地址 需要使用内网穿透工具（花生壳）
  notifyurl: http://www.itcast.cn

#位置支付交换机和队列
mq:
  pay:
    exchange:
      order: exchange.order
    queue:
      order: queue.order
    routing:
      key: queue.order
