spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: file
  redis:
    host: 150.158.213.196
    password: mypassword
  main:
    allow-bean-definition-overriding: true

server:
  port: 18082
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    instance:
      prefer-ip-address: true
#feign:
#  hystrix:
#    enabled: true
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000