server:
  port: 18083
spring:
  application:
    name: community
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schedule_community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 150.158.213.196
    password: mypassword
  main:
    allow-bean-definition-overriding: true

#  cloud:
#    alibaba:
#      seata:
#        tx-service-group: my_test_tx_group
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    instance:
      prefer-ip-address: true
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
